### ISSUE TITLE
error clicking buttons 

### ISSUE THREAD

**Issue by Zhongli8726** [Merubokkusu/Discord-S.C.U.M#252]
![image](https://user-images.githubusercontent.com/95374354/144489942-c66241e3-172c-4fdc-b023-44cb5e96a5ce.png)
getting this error ive installed the latest version from github directly
_________
arandomnewaccount:
how are you getting the msg_data? It should be a dictionary, not a list.

**Comment by ghost** [comment]
How frequently are you clicking the button/checking for presses? I noticed this same error while running discum on my main machine and getting guild-names from guild-ids too frequently, and i wasn't able to find a work-around. If you can somehow check less for clicks or just click it less, try to do that and see if it fixes the issue.
____________
arandomnewaccount:
i believe that's a different issue. You're prob getting 429 status codes (rate limited) from checking guild names too often. I'd recommend using the gateway instead of rest api reqs to not get 429 status codes.
Zhongli8726's error shows that they set msg_data to be a list. That leads me to assume that maybe they set msg_data to the components of the message (instead of the entire message dictionary).

edit: closing as inactive

**Comment by ghost** [comment]
ohhh okay
