### ISSUE TITLE
Discussion: Recommended way of using createDMs?

### ISSUE THREAD

**Issue by b-hasbmans** [Merubokkusu/Discord-S.C.U.M#41]
Just wanted to ask if there are any recommended best practices for using `createDM` as you mention it is one of the calls to be careful with.

Any recommendations on how frequently it's ok to call? Every other second? Every 10 seconds?  Is it better to call with many user ids at once or separately for each?  If nobody knows, that's ok, I realize some of it is up to personal taste for risk, but wanted to check. Thanks!

________________________________
arandomnewaccount:
Btw, I'm going to wait until I run a few more tests with the createDM endpoint (& organize some code in RESTapiwrap.py) until I give my recommendations on this. If anyone else has some more experience with creating DMs, feel free to jump in.

**Comment by Raidr1212** [comment]
Any updates?
________
arandomnewaccount:
mini update ig...
Personally, I haven't gotten createDM to safely work yet. Therefore, as of right now, I can't actually make good recommendations. However, I can say what (sorta) hasn't failed and what has failed.

So I ran a few tests in my browser with blocking some endpoints and it seems that blocking science endpoints doesn't matter but blocking endpoints for getting messages (getMessages) and getting user notes (getNotes) does matter. Also, I'm not sure yet, but blocking the getProfile endpoint might matter. These other endpoints seem to matter since they're run when you create a new DM. 

Specifically, the order is:
1. get user getNotes
2. [gateway] lazy guild with members = [userID]
3. create DM
4. [gateway] request channel view
5. get messages (num=50)
6. get profile of userID
7. send message

It's possible that the gateway part doesn't matter. I'm not certain yet. The reason I'm not certain is because I tried only doing the REST requests and my acc got locked. I then tried doing both the REST requests and the gateway part and my acc got locked. For reference, here's the code I used: https://pastebin.com/YbnxXHjZ

and here's the general code structure I'm using:
```python
@bot.gateway.command
def missionFailed(resp):
	if resp.event.required_action_updated:
		print("mission failed :(")
		bot.gateway.clearCommands()
		bot.gateway.resetSession()
		bot.gateway.close()

def createDMandSend(resp, ...):
	if resp.event.ready_supplemental:
		...<code here for sending a direct msg>...

bot.gateway.command({"function": createDMandSend, "params":{...}})

bot.gateway.run()
```

Therefore, I can think of one of three possibilities. Either more user actions (other than the 7 listed above) need to be used (such as lazy guild for a guild channel, get messages on a guild channel, etc), science requests need to be used, or the selfbot detection takes into account other variables.

So, yea, that's where I am in testing this, currently. I guess I'll add the answered label; idk if you all get updates whenever I edit responses.

**Comment by arghiz** [comment]
Hi sir, is there any discord support available for this module/lib?

Also, what is the command equivalent to wait_for?
When I send a command message, I want to get the respond and process it.

Please advice.
____________________
arandomnewaccount:
Please create a new issue if you have a different problem. This issue is only for creating DMs.

**Comment by cvcci** [comment]
Works on aged account no lock.

Created: Fri, 27 Dec 2019 23:55:17 UTC

**Comment by cvcci** [comment]
![image](https://user-images.githubusercontent.com/66767915/117523940-0db0c100-af89-11eb-982c-35cbcc7acdba.png)
the moment i tried to mass dm (I failed but got insta tapped only sent 1 message to my own account)
________________
arandomnewaccount:
small update: creating DMs worked just fine with a browser automator. I could even send messages and my account did not get phone locked. However, there're some restrictions as to who you can dm; you can only DM ppl that are in a member list.

The reason for this is that you need to get a user profile popup in order to create the DM. Only members from the member list have this popup. Indeed, you don't have to click on a member in the member list to start a DM with that member (you can, instead, click on a mention of that user). But, if the data for that user has not been cached by the client (which is done by scrolling thru the member list), you cannot get a create DM popup for that user.

Btw, by user popup, I'm referring to this:
<img width="250" alt="popupexample" src="https://user-images.githubusercontent.com/68355905/119075031-17d9b300-b9be-11eb-889f-d5de7f343b46.png">

**Comment by guoguoguilai** [comment]
Any update?
______
arandomnewaccount:
I believe I (at least partially) fixed this in one of the latest commits. I used createDM on an alt and did not get phone locked. Feel free to try the new functions and see if they work on your end. Be sure to use good proxies and prob put a wait time between createDMs.

edit: moving discussion from this issue to https://github.com/Merubokkusu/Discord-S.C.U.M/issues/66

**Comment by cth-latest** [comment]
I wanted to update on something, don't you think that the client is sending a "typing" update as we can see peoples writing ? 

(I talk about "xxxx is writing ...")

Official bots are also able to simulate the wrinting.

**Comment by 1trackprojects1** [comment]
Has anyone figured this out yet?

**Comment by thunderstorm010** [comment]
> I wanted to update on something, don't you think that the client is sending a "typing" update as we can see peoples writing ?
> 
> (I talk about "xxxx is writing ...")
> 
> Official bots are also able to simulate the wrinting.

https://discord.com/developers/docs/resources/channel#trigger-typing-indicator
