### ISSUE TITLE
Websocket closed after some time

### ISSUE THREAD

**Issue by rb1997** [Merubokkusu/Discord-S.C.U.M#65]
When running the script for a few hours, the log says websocket closed and the script exits. What could be causing this and is there a known solution? 

Thanks!
_________________________
arandomnewaccount:
did you install from pypi or from the github repo?

**Comment by rb1997** [comment]
installed using pip / pypi
__________________
arandomnewaccount:
ah ok. The pypi is 2 versions behind the github. So, just uninstall the pypi version (```pip uninstall discum```) and install directly from the github repo (```python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git```)

**Comment by rb1997** [comment]
Thanks, just reinstalled using git, will see how it goes :)

**Comment by hungrybeagle** [comment]
I am having the same issue... socket seems to close in under an hour. I upgraded to 1.2.1 but no better
_____________________
arandomnewaccount:
under an hour? That's new. Which python version are you using?

**Comment by akbar-amin** [comment]
It may be due to this not being handled correctly:

> The gateway may request a heartbeat from the client in some situations by sending an Opcode 1 Heartbeat. When this occurs, the client should immediately send an Opcode 1 Heartbeat without waiting the remainder of the current interval.

This is from the [heartbeat section](https://discord.com/developers/docs/topics/gateway#heartbeating) in the developer docs.

I don't recall seeing this in the documentation before, but I may be wrong. Nothing in the changelog hints it was added. In any case, if the gateway is sending more than one "HELLO" event, the [handling](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/dc158a2d24b2f201a3ca51906be2ee1613eeb4ad/discum/gateway/gateway.py#L175) for it needs to be reworked so that it doesn't collide with the current heartbeat thread.
_____________________________
arandomnewaccount:
hm. Well I'm still getting the feeling that @hungrybeagle 's disconnects are not related to heartbeats since the current reconnection implementation in discum reconnects unless the user does ```bot.gateway.close()``` or ctrl-c. So, even if the dev/user were to send a wrongly formatted msg to the gateway (which would cause discord to close the connection), discum would still reconnect. So, @hungrybeagle, could send the log and any errors you got (don't forget to remove your token from the logs)?

However, it's still important that you, @akbar-amin, bring that up. 
Interestingly, I don't recall seeing any opcode 1s coming from discord (neither in my discum tests nor in the official client). 
Anyway, It shouldn't be too tricky to implement a handler for this into discum, so long as it is independent of the current heartbeat thread.

Also, multiple hello events would be.....weird. But eh ig anythings possible with discord's weird api. I'll be on the lookout for 
"duplicate" HELLO events.

On a side note, I know that gateway reconnections should depend on close codes. The reason they haven't for discum so far is because websocket-client was not sending back any close codes. This seemed to have changed yesterday (https://github.com/websocket-client/websocket-client/issues/686), so I'll be doing some tests and hopefully, finally, making the reconnection handling mimic the official client.
pushed a few updates, next push will include close codes among other updates

**Comment by hungrybeagle** [comment]
Running Python 3.8.5

Not sure if this is what you're looking for... log set to True![image](https://user-images.githubusercontent.com/47019600/117518349-408c9200-af54-11eb-9185-ff134b705eb2.jpeg)

I don't have it trying to close or anything, I'm just using it to read all messages as they come up, filter the ones from specific categories and forward them to a telegram so I can see them all in one place.  I've worked around it by just placing the whole program in a while True loop so that as soon as it disconnects, it reinitializes the client and continues on
__________________
arandomnewaccount:
huh, that's weird, you shouldn't have to put it in a while loop. Here, it might be easier to debug this if we chat. You can email me at discordtehe@gmail.com and we can continue from there.
And then, after we figure out what's going on, I'll write here what the issue was so other ppl can see it too.

**Comment by vivinano** [comment]
I believe my app is also breaking when this happens so as soon as the websocket closes then im suck in a infinite send loop

> ![image](https://user-images.githubusercontent.com/33008397/117882835-b9ebf380-b278-11eb-9bf4-b802203240c5.png)
____________________________
arandomnewaccount:
gonna run a test for a day and see if I can replicate those results on my end. 
Btw (1) which python version are you running and (2) what discum version are you using?

**Comment by vivinano** [comment]
Python 3.8.5  and disum 1.2.1
_________
arandomnewaccount:
alr, thx. Made some changes to gateway.py so either reinstall or copy-paste the new gateway.py file into your installation location. I'll keep running it on my end but it seems to have fixed the error. Let me know if you run into any problems.

**Comment by vivinano** [comment]
Been running my selfbot for 24 hours I think the issue has been fixed with the changes to gateway.py
_____________
nice ok. I've also been running bot.gateway.run() on my end for the past ~1.5 days and it's been running smoothly.

edit: still running a version on my end and it's been running smoothly. I'll be closing this issue - feel free to open up another one if gateway reconnection issues arise when using the most up-to-date version of discum.
