### ISSUE TITLE
Installing on replit

### ISSUE THREAD

**Issue by oxy-Op** [Merubokkusu/Discord-S.C.U.M#77]
I cannot install discum in https://replit.com , ```pip install discum -U``` Didn't Work Error : Module Discum not found / I have tried cloning discum and also importing but nothing works

Please How can i install discum to [https://replit.com](replit)
_______________
arandomnewaccount:
ignore my previous answer. I found a nicer-looking way:
```
try:
    import discum
except:
    import os
    os.system("pip install git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum")
    import discum
```

**Comment by milkycereal** [comment]
Go to shell and type ``pip install discum``
______________
arandomnewaccount:
installing from pypi is not recommended since the pypi version is currently on v1.1.0 (while the github repo is on v1.2.1).
For details on what's been changed between these versions, you can check the [changelog](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/changelog.md).

Closing this as answered.
